name: "✨ 작업 템플릿"
description: "새로운 기능, 버그 수정 등 작업을 생성할 때 사용합니다."
title: "[작업 유형] 간단한 작업 제목"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 작업 템플릿
        새로운 기능 추가, 버그 수정, 리팩토링 등 작업을 생성하기 위한 템플릿입니다. 아래 필드를 채워주세요.
  - type: checkboxes
    id: issue-type
    attributes:
      label: 이슈 유형
      description: 해당하는 작업 유형을 모두 선택해주세요. (최소 1개 필수)
      options:
        - label: 🚀 Feat: 새로운 기능 추가
        - label: 🐛 Fix: 버그 수정
        - label: 🛠 Refactor: 코드 구조 개선
        - label: 📄 Docs: 문서 관련 작업
        - label: 🧹 Chore: 기타 관리 작업
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### 작업 내용 작성 가이드
        아래 가이드를 참고하여 작업 내용을 구체적으로 작성해주세요.

        **🚀 Feat: 새로운 기능 추가**
        - 추가하려는 기능에 대해 구체적으로 작성해주세요.
        - 예: 사용자가 OO을 할 수 있도록 OO 기능을 추가합니다.

        **🐛 Fix: 버그 수정**
        - 어떤 버그가 발생했고, 어떻게 수정할 계획인지 작성해주세요.
        - 예: 특정 조건에서 로그인 시 발생하던 500 에러를 해결합니다.

        **🛠 Refactor: 코드 구조 개선**
        - 어떤 부분을 리팩토링하고, 개선된 점은 무엇인지 작성해주세요.
        - 예: 중복된 인증 로직을 `AuthService`로 통합하여 관리 포인트를 줄입니다.

        **📄 Docs: 문서 관련 작업**
        - 어떤 문서를 추가하거나 수정할 것인지 작성해주세요.
        - 예: 프로젝트 README.md 파일에 새로운 API 사용법을 추가합니다.

        **🧹 Chore: 기타 관리 작업**
        - 빌드 스크립트, 의존성 업데이트 등 기타 내용을 작성해주세요.
        - 예: `requests` 라이브러리 버전을 `2.25.1`에서 `2.28.0`으로 업데이트합니다.
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 작업 내용을 구체적으로 작성해주세요. 위 가이드를 참고하세요.
      placeholder: 여기에 작업 내용을 입력하세요.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 작업과 관련된 추가 정보나 참고 자료를 작성해주세요. (선택)
      placeholder: 예: 관련 이슈 #123, 참고 문서 링크 등
    validations:
      required: false
